### ISSUE TITLE
[Suggestion] Separate the django website in another repo

### ISSUE THREAD

**Issue by CyberFox001** [rafalp/misago_docker#101]
## The problem

This repository, `misago_docker`, provide a very useful tool to deploy Misago on a dedicated server with Docker installed on it.

But, this solution is not very flexible: It require Docker and it will install the full software stack needed by Misago, reverse proxy included. Which mean if you use `misago_docker`, you need a dedicated server.

If someone want to use another container engine, like Kubernetes or Podman, it's not possible. If someone already have a reverse proxy, or want to control exactly how the software stack is deployed with tools like Ansible, it's not possible.

## The suggestion

The suggestion is to separate the actual `misago_docker` in two parts. Part one: A reusable and documented container image of Misago. Part two: This repository, that reuse the Misago container image.

It could be made in a few steps:
  * Make a separate repository, with a django website configured to use Misago app and ready to use in production
  * In this repo, provide a simple `Dockerfile` to make a container image of this ready to use website
  * Provide an official container image on the Docker Hub made from this repo
  * Document how to run and config this website, as a container or not
  * Document what software stack is needed, and how to configure everyone to work together
  * Modify `misago_docker` to use the new official container image instead of the actual `./miago` directory

With this solution, if someone want something more flexible, it can user the new container image and it's documentation. Adapt it to it's own infrastructure. And `misago_docker` can still be used as today.

It's just a suggestion. What do you think ?

**Comment by rafalp** [comment]
Why not create those two repositories and maintain them yourself? You can advertise them on official forums and get a link in readme from this repo and official docs, if you do the work and stick around and maintain them :)

**Comment by CyberFox001** [comment]
I could, but do I have enough knowledge about the project to do it ?

I mean, I already deploy a Misago instance, but I still search how to show the categories I created in the home page. :sweat_smile:

**Comment by rafalp** [comment]
The reason why I'm against doing this myself is because over those 10 years of working on Misago I've learned first hand that only thing that giving people a choice in how they deploy Misago accomplishes is that now in addition to me having to deal with Misago itself, I also have to deal with people setups.

Your approach will result in following things to happen:

- A lot of people will pick the "just misago" image as starting point because they think they know better how to setup their site.
- Those people will come to me for help because they will have problems setting up their Misago site.
- Those people will walk away thinking that Misago is some overengineered piece of crap software because they failed to get cron to work, or message queue for celery to work or media files storage to work or whatever.

With how things are currently, I have single repo that requires minimal maintenance from me to do, and I can tell people "if you want forum on Misago, here's the guide and here's the work's out of the box setup". It works because it's opinionated and all the complexity is hidden away from the people.

If what you are suggesting worked, Discourse would've done it years ago with their `discourse-docker` package, and yet they don't, despite employing two dozens of people working on it fulltime and people on their forums requesting this option constantly. For some reason all those people arguing on their forums that its actually easy and they'll do it themselves either don't do it at all, or give up weeks into it.

Sorry for sounding so harsh here, but I've been doing this stuff for so long now that I've learned to spot patterns from mile away.

> I still search how to show the categories I created in the home page.

https://misago-project.org/t/new-categories-are-not-showing/922/#post-4193

**Comment by CyberFox001** [comment]
I can see why you don't want to provide a documented container image but only a full deployment scripts. But as is, I can't use `misago_docker` directly on our infrastructure.

I can still use Misago, in a deployment adapted to our infrastructure. That why I built an image from the `misago/` folder and study the `docker-compose.yaml`, the `wizard/` scripts, the `appctl` script and the application code to deploy and configure all needed software on our infrastructure with Ansible. My suggestion was to not make the work on my side if it can be made upstream.

For now, we are testing Misago at our association to see if it suits our community. Testing its features, look how we can use it.
If we keep it for our forum, I can make an unofficial container image, publish it on a public git repo, document how to use it and provide an example of Ansible Playbook to deploy it.

Any suggestion on the name, to not make confusion with the official project ?

**Comment by rafalp** [comment]
You can just prefix the name of your things with something custom, like „cfox-misago-image”, „cfox-misago-compose” or „cfox-misago-podman” ;)

**Comment by rafalp** [comment]
Closing as I am not going to do this for reasons explained above.
